# Generated by Django 4.2.3 on 2023-07-19 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.CharField(choices=[('COMPUTER SCIENCES', 'COMPUTER SCIENCES'), ('BIOLOGICAL SCIENCES', 'BIOLOGICAL SCIENCES'), ('CHEMICAL SCIENCES', 'CHEMICAL SCIENCES'), ('MANAGEMENT SCIENCES', 'MANAGEMENT SCIENCES'), ('MASS COMMUNICATION', 'MASS COMMUNICATION'), ('CRIMINOLOGY', 'CRIMINOLOGY'), ('GENERAL STUDIES', 'GENERAL STUDIES')], max_length=250),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_of_teaching', models.PositiveIntegerField()),
                ('communication', models.PositiveIntegerField()),
                ('relationship', models.PositiveIntegerField()),
                ('comment', models.CharField(max_length=1000)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MySite.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MySite.student')),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.DecimalField(decimal_places=2, max_digits=5)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MySite.course')),
            ],
        ),
    ]
